# Generated by Django 6.0.7 on 2026-07-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched_subreddit', models.CharField(max_length=30)),
                ('total_fetched_posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=15)),
                ('author_username', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('service_category', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('estimated_value', models.FloatField(default=0)),
                ('is_good_lead', models.BooleanField(default=False)),
                ('buying_intent', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=20)),
                ('competition', models.CharField(max_length=20)),
                ('recommended_action', models.CharField(max_length=20)),
                ('matched_keywords', models.JSONField()),
                ('ai_review', models.TextField()),
                ('suggested_replies', models.JSONField()),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subreddit')),
            ],
        ),
    ]
