# Generated by Django 6.0.7 on 2026-07-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlead',
            name='categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postlead',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postlead',
            name='posted_when',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.subreddit'),
        ),
    ]
