# Generated by Django 6.0.7 on 2026-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postlead_categorized_postlead_number_of_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlead',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
