# Generated by Django 6.0.7 on 2026-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_postlead_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlead',
            name='buying_intent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='competition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='matched_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='recommended_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='service_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='suggested_replies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='urgency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
