# Generated by Django 6.0.7 on 2026-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_postlead_buying_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlead',
            name='author_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
