# Generated by Django 6.0.7 on 2026-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_postlead_author_username_alter_postlead_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlead',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
