# Generated by Django 6.0.7 on 2026-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postlead_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Ignored', 'Ignored'), ('Waiting', 'Waiting'), ('Replied', 'Replied'), ('Dm', 'Dm'), ('Call booked', 'Call Booked'), ('Proposal sent', 'Proposal Sent'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
