# Generated by Django 6.0.7 on 2026-07-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postlead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlead',
            name='ai_review',
            field=models.TextField(blank=True, default='', help_text='A concise AI-generated explanation of the lead quality, business fit, buying intent, urgency, and competition.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='author_username',
            field=models.CharField(blank=True, help_text='The Reddit username of the post author. This may be empty if the account was deleted.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='buying_intent',
            field=models.CharField(blank=True, help_text='The estimated likelihood that the author intends to hire or purchase a service, such as high, medium, low, or none.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='categorized',
            field=models.BooleanField(default=False, help_text='Indicates whether this post has already been analyzed and categorized by the AI.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='competition',
            field=models.CharField(blank=True, help_text='The estimated level of competition from other developers or agencies responding to the post.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='content',
            field=models.TextField(help_text='The main text content of the Reddit post.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='estimated_value',
            field=models.FloatField(default=0, help_text='The AI-estimated potential project value in US dollars.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='is_good_lead',
            field=models.BooleanField(default=False, help_text='Indicates whether the AI considers this post a worthwhile sales lead.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='matched_keywords',
            field=models.JSONField(blank=True, help_text='A list of relevant words or phrases found in the post that influenced the AI analysis.', null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='number_of_comments',
            field=models.IntegerField(default=0, help_text='The number of comments the Reddit post had when it was last fetched.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='post_id',
            field=models.CharField(help_text='The unique Reddit ID assigned to this post.', max_length=15),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='posted_when',
            field=models.CharField(blank=True, help_text='A readable version of the date and time when the post was published.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='recommended_action',
            field=models.CharField(blank=True, help_text='The AI-recommended next step for this lead, such as reply, watch, or ignore.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='score',
            field=models.IntegerField(default=0, help_text='The AI-generated lead quality score from 0 to 100. Higher scores indicate stronger commercial opportunities.'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='service_category',
            field=models.CharField(blank=True, help_text='The service category assigned by the AI, such as website, Shopify, bot, automation, chatbot, or other.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Ignored', 'Ignored'), ('Waiting', 'Waiting'), ('Replied', 'Replied'), ('Dm', 'DM sent'), ('Call booked', 'Call booked'), ('Proposal sent', 'Proposal sent'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', help_text='The current sales pipeline stage for this lead, from New through Won or Lost.', max_length=20),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='subreddit',
            field=models.ForeignKey(help_text='The subreddit where this post was discovered.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.subreddit'),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='suggested_replies',
            field=models.JSONField(blank=True, help_text='AI-generated Reddit reply suggestions tailored to the content of this post.', null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this lead was first saved.', null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='urgency',
            field=models.CharField(blank=True, help_text="The estimated urgency of the author's request, such as high, medium, low, or none.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postlead',
            name='url',
            field=models.URLField(blank=True, help_text='The direct URL to the original Reddit post.', null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(help_text="The subreddit to monitor. You may enter it as 'webdev' or 'r/webdev'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='last_fetched_subreddit',
            field=models.CharField(blank=True, default='', help_text='The most recent subreddit processed by the Reddit post-fetching task.', max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='total_fetched_posts',
            field=models.IntegerField(default=0, help_text='The total number of new Reddit posts saved during the latest fetch.'),
        ),
    ]
