# Generated by Django 6.0.7 on 2026-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_postlead_ai_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditBotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='The client ID of this account gotten from https://www.reddit.com/prefs/apps ', max_length=100)),
                ('client_secret', models.CharField(help_text='The client secret of this account gotten from https://www.reddit.com/prefs/apps ', max_length=150)),
                ('is_active', models.BooleanField(default=False, help_text='This activates or deactivates a bot account ')),
                ('last_run', models.DateTimeField(blank=True, help_text='When last this bot account ran', null=True)),
            ],
        ),
    ]
