# Generated by Django 6.0.7 on 2026-07-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_redditbotaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlead',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The bot account that fetched this post lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.redditbotaccount'),
        ),
    ]
