# Generated by Django 6.0.7 on 2026-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postlead_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditbotaccount',
            name='user_agent',
            field=models.CharField(default='', help_text='The user agent of this account', max_length=20),
        ),
    ]
