# Generated by Django 6.0.7 on 2026-07-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_redditbotaccount_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email to be notified when post fetching and categorization is complete', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='redditbotaccount',
            name='categorization_complete_email_recipient',
            field=models.ForeignKey(blank=True, help_text='The email address that will be notified when the AI has finished fetching and categorizing posts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailfornotification'),
        ),
    ]
