from django.contrib import admin
from .models import Tracker, Subreddit, PostLead
from import_export.admin import ImportExportModelAdmin
from django.utils.html import format_html, format_html_join
from django.utils.safestring import mark_safe

class TrackerAdmin(ImportExportModelAdmin, admin.ModelAdmin):
    list_display = ['last_fetched_subreddit', 'total_fetched_posts']

admin.site.register(Tracker, TrackerAdmin)

class SubredditAdmin(ImportExportModelAdmin, admin.ModelAdmin):
    list_display = ['name']

admin.site.register(Subreddit, SubredditAdmin)

class PostLeadAdmin(ImportExportModelAdmin, admin.ModelAdmin):
    list_display = (
        "post_id",
        "subreddit",
        "service_category_badge",
        "lead_score_badge",
        "good_lead_badge",
        "recommended_action_badge",
        "status",
        "posted_when",
        "timestamp",
    )

    search_fields = (
        "post_id",
        "subreddit__name",
        "author_username",
        "content",
        "ai_review",
    )

    list_filter = (
        "subreddit",
        "status",
        "service_category",
        "is_good_lead",
        "buying_intent",
        "urgency",
        "competition",
        "recommended_action",
        "timestamp",
    )

    list_select_related = ("subreddit",)

    ordering = ("-timestamp",)

    date_hierarchy = "timestamp"

    list_per_page = 25

    # Fields generated by Reddit/OpenAI should not be manually changed.
    readonly_fields = (
        # Reddit/source information
        "post_id",
        "author_username",
        "content",
        "number_of_comments",
        "url",
        "posted_when",
        "timestamp",

        # Internal processing state
        "categorized",

        # AI presentation fields
        "ai_lead_overview",
        "ai_classification",
        "ai_review_display",
        "matched_keywords_display",
        "suggested_replies_display",

        # Raw AI-generated model fields
        "service_category",
        "score",
        "estimated_value",
        "is_good_lead",
        "buying_intent",
        "urgency",
        "competition",
        "recommended_action",
        "matched_keywords",
        "ai_review",
        "suggested_replies",
    )

    fieldsets = (
        (
            "Reddit Post",
            {
                "fields": (
                    "subreddit",
                    ("post_id", "author_username"),
                    "content",
                    ("number_of_comments", "posted_when"),
                    "url",
                ),
                "description": (
                    "Original information collected from the Reddit post."
                ),
            },
        ),
        (
            "AI Lead Analysis",
            {
                "fields": (
                    "ai_lead_overview",
                    "ai_classification",
                    "ai_review_display",
                    "matched_keywords_display",
                    "suggested_replies_display",
                ),
                "description": (
                    "This information was generated automatically during AI "
                    "categorization and cannot be edited manually."
                ),
            },
        ),
        (
            "Sales Pipeline",
            {
                "fields": (
                    "status",
                ),
                "description": (
                    "Update the lead's progress as you contact the Reddit user."
                ),
            },
        ),
        (
            "System Information",
            {
                "fields": (
                    "categorized",
                    "timestamp",
                ),
                "classes": ("collapse",),
                "description": (
                    "Internal processing information used by the application."
                ),
            },
        ),
    )

    # Controls the order of Jazzmin sections/tabs.
    jazzmin_section_order = (
        "Reddit Post",
        "AI Lead Analysis",
        "Sales Pipeline",
        "System Information",
    )

    @admin.display(description="AI lead overview")
    def ai_lead_overview(self, obj):
        if not obj or not obj.categorized:
            return self._empty_analysis_message()

        score = obj.score or 0
        score_color = self._score_color(score)

        lead_text = "Good lead" if obj.is_good_lead else "Weak lead"
        lead_color = "#198754" if obj.is_good_lead else "#6c757d"

        estimated_value = obj.estimated_value or 0

        return format_html(
            """
            <div style="
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
                gap: 12px;
                margin: 5px 0 10px 0;
            ">
                <div style="
                    padding: 16px;
                    border: 1px solid #dee2e6;
                    border-radius: 8px;
                    background: #ffffff;
                ">
                    <div style="
                        color: #6c757d;
                        font-size: 12px;
                        text-transform: uppercase;
                        font-weight: 600;
                        margin-bottom: 6px;
                    ">
                        Lead score
                    </div>

                    <div style="
                        color: {};
                        font-size: 26px;
                        font-weight: 700;
                    ">
                        {}/100
                    </div>
                </div>

                <div style="
                    padding: 16px;
                    border: 1px solid #dee2e6;
                    border-radius: 8px;
                    background: #ffffff;
                ">
                    <div style="
                        color: #6c757d;
                        font-size: 12px;
                        text-transform: uppercase;
                        font-weight: 600;
                        margin-bottom: 6px;
                    ">
                        Lead quality
                    </div>

                    <span style="
                        display: inline-block;
                        padding: 5px 10px;
                        border-radius: 20px;
                        color: #ffffff;
                        background: {};
                        font-weight: 600;
                    ">
                        {}
                    </span>
                </div>

                <div style="
                    padding: 16px;
                    border: 1px solid #dee2e6;
                    border-radius: 8px;
                    background: #ffffff;
                ">
                    <div style="
                        color: #6c757d;
                        font-size: 12px;
                        text-transform: uppercase;
                        font-weight: 600;
                        margin-bottom: 6px;
                    ">
                        Estimated value
                    </div>

                    <div style="
                        color: #212529;
                        font-size: 26px;
                        font-weight: 700;
                    ">
                        ${:,.0f}
                    </div>
                </div>
            </div>
            """,
            score_color,
            score,
            lead_color,
            lead_text,
            estimated_value,
        )

    @admin.display(description="AI classification")
    def ai_classification(self, obj):
        if not obj or not obj.categorized:
            return "The post has not been categorized yet."

        items = (
            ("Service category", obj.service_category),
            ("Buying intent", obj.buying_intent),
            ("Urgency", obj.urgency),
            ("Competition", obj.competition),
            ("Recommended action", obj.recommended_action),
        )

        return format_html(
            """
            <div style="
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                gap: 10px;
            ">
                {}
            </div>
            """,
            format_html_join(
                "",
                """
                <div style="
                    padding: 12px;
                    border-left: 4px solid {};
                    background: #f8f9fa;
                    border-radius: 5px;
                ">
                    <div style="
                        color: #6c757d;
                        font-size: 11px;
                        font-weight: 600;
                        text-transform: uppercase;
                        margin-bottom: 5px;
                    ">
                        {}
                    </div>

                    <div style="
                        color: #212529;
                        font-weight: 600;
                        text-transform: capitalize;
                    ">
                        {}
                    </div>
                </div>
                """,
                (
                    (
                        self._classification_color(label, value),
                        label,
                        value or "Not available",
                    )
                    for label, value in items
                ),
            ),
        )

    @admin.display(description="AI review")
    def ai_review_display(self, obj):
        if not obj or not obj.ai_review:
            return "No AI review is available."

        return format_html(
            """
            <div style="
                padding: 16px;
                border-left: 4px solid #0d6efd;
                border-radius: 6px;
                background: #f8f9fa;
                line-height: 1.6;
                white-space: pre-wrap;
                max-width: 1000px;
            ">
                {}
            </div>
            """,
            obj.ai_review,
        )

    @admin.display(description="Matched keywords")
    def matched_keywords_display(self, obj):
        keywords = obj.matched_keywords or []

        if not isinstance(keywords, list) or not keywords:
            return "No matched keywords were identified."

        return format_html_join(
            " ",
            """
            <span style="
                display: inline-block;
                margin: 3px 4px 3px 0;
                padding: 5px 10px;
                border-radius: 20px;
                background: #e9ecef;
                color: #343a40;
                font-size: 12px;
                font-weight: 600;
            ">
                {}
            </span>
            """,
            ((keyword,) for keyword in keywords),
        )

    @admin.display(description="Suggested Reddit replies")
    def suggested_replies_display(self, obj):
        replies = obj.suggested_replies or []

        if not isinstance(replies, list) or not replies:
            return "No suggested replies were generated."

        return format_html_join(
            "",
            """
            <div style="
                position: relative;
                margin-bottom: 14px;
                padding: 16px 16px 16px 52px;
                border: 1px solid #dee2e6;
                border-radius: 8px;
                background: #ffffff;
                line-height: 1.6;
                white-space: pre-wrap;
                max-width: 1000px;
            ">
                <span style="
                    position: absolute;
                    top: 14px;
                    left: 14px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    width: 26px;
                    height: 26px;
                    border-radius: 50%;
                    background: #0d6efd;
                    color: #ffffff;
                    font-size: 12px;
                    font-weight: 700;
                ">
                    {}
                </span>
                {}
            </div>
            """,
            (
                (index, reply)
                for index, reply in enumerate(replies, start=1)
            ),
        )

    @staticmethod
    def _soft_badge(text):
        return format_html(
            """
            <span style="
                display: inline-block;
                padding: 3px 8px;
                border: 1px solid #dfe3e8;
                border-radius: 6px;
                background: #f7f8fa;
                color: #555c65;
                font-size: 12px;
                font-weight: 600;
                white-space: nowrap;
            ">
                {}
            </span>
            """,
            text,
        )

    @admin.display(description="Category")
    def service_category_badge(self, obj):
        if not obj.service_category:
            return mark_safe(
                '<span style="color:#8a8f98;">Not categorized</span>'
            )

        return self._soft_badge(obj.service_category.title())

    @admin.display(description="Score", ordering="score")
    def lead_score_badge(self, obj):
        score = obj.score or 0

        return format_html(
            """
            <span style="
                display: inline-block;
                min-width: 50px;
                padding: 3px 8px;
                border: 1px solid #dfe3e8;
                border-radius: 6px;
                background: #f7f8fa;
                color: #495057;
                font-size: 12px;
                font-weight: 600;
                text-align: center;
            ">
                {}/100
            </span>
            """,
            score,
        )
        
    @admin.display(description="Good lead", ordering="is_good_lead")
    def good_lead_badge(self, obj):
        if obj.is_good_lead:
            text = "Yes"
            border_color = "#cfe4d6"
            background_color = "#f1f8f3"
            text_color = "#477257"
        else:
            text = "No"
            border_color = "#dfe3e8"
            background_color = "#f7f8fa"
            text_color = "#747b84"

        return format_html(
            """
            <span style="
                display: inline-block;
                padding: 3px 8px;
                border: 1px solid {};
                border-radius: 6px;
                background: {};
                color: {};
                font-size: 12px;
                font-weight: 600;
            ">
                {}
            </span>
            """,
            border_color,
            background_color,
            text_color,
            text,
        )

    @admin.display(description="Action", ordering="recommended_action")
    def recommended_action_badge(self, obj):
        action = obj.recommended_action

        if not action:
            return mark_safe(
                '<span style="color:#8a8f98;">Not available</span>'
            )

        return self._soft_badge(action.title())

    @staticmethod
    def _badge(text, background_color):
        return format_html(
            """
            <span style="
                display: inline-block;
                padding: 4px 9px;
                border-radius: 20px;
                background: {};
                color: #ffffff;
                font-size: 11px;
                font-weight: 700;
                white-space: nowrap;
            ">
                {}
            </span>
            """,
            background_color,
            text,
        )

    @staticmethod
    def _score_color(score):
        if score >= 80:
            return "#198754"

        if score >= 60:
            return "#0d6efd"

        if score >= 40:
            return "#fd7e14"

        return "#dc3545"

    @staticmethod
    def _classification_color(label, value):
        value = (value or "").lower()

        if label == "Recommended action":
            return {
                "reply": "#198754",
                "watch": "#fd7e14",
                "ignore": "#6c757d",
            }.get(value, "#6c757d")

        if value == "high":
            return "#198754"

        if value == "medium":
            return "#fd7e14"

        if value in {"low", "none"}:
            return "#6c757d"

        return "#0d6efd"

    @staticmethod
    def _empty_analysis_message():
        return mark_safe(
            """
            <div style="
                padding: 15px;
                border-left: 4px solid #fd7e14;
                border-radius: 5px;
                background: #fff3cd;
                color: #664d03;
            ">
                This Reddit post has not been analyzed by the AI yet.
                Run the categorization task to generate the analysis.
            </div>
            """
        )

admin.site.register(PostLead, PostLeadAdmin)